packages:
  - .
  - examples/*

catalog:
  solid-js: ^2.0.0-experimental.16
  "@solidjs/web": ^2.0.0-experimental.16

ignoredBuiltDependencies:
  - cypress

onlyBuiltDependencies:
  - cypress
  - esbuild
  - msw
